name: Testes do Backend

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Iniciar backend e rodar testes
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/backend.cy.js
          start: node backend/server.js
          wait-on: 'http://localhost:3001/tasks'